import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import PaDaKaPanyHeader from "@/app/PaDaKaPanyHeader";
import Link from 'next/link'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
            <script type='text/javascript'
                    src='https://raw.githack.com/AR-js-org/AR.js/master/three.js/build/ar-threex-location-only.js'></script>
            <script type='text/javascript'
                    src='https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js'></script>
        </head>
        <body className={inter.className}>
        <Link href="/"><span
            style={{textDecoration: "underline", position: "fixed", top: 10, left: 10, color: "white", zIndex: 9999}}>Location</span></Link>
        <Link href="/marker"
              style={{textDecoration: "underline", position: "fixed", top: 10, left: 100, color: "white", zIndex: 9999}}><span>Marker</span></Link>
        <PaDaKaPanyHeader/>
        {children}
        </body>
        </html>
    )
}
