import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PaDaKaPanyHeader from "@/app/PaDaKaPanyHeader";
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <Link href="/"><span
                    style={{ textDecoration: "underline", position: "fixed", top: 40, left: 10, color: "white", zIndex: 9999 }}>Location</span></Link>
                <Link href="/marker"
                    style={{ textDecoration: "underline", position: "fixed", top: 40, left: 90, color: "white", zIndex: 9999 }}><span>Marker</span></Link>
                <Link href="/image"
                    style={{ textDecoration: "underline", position: "fixed", top: 40, left: 162, color: "white", zIndex: 9999 }}><span>Image</span></Link>
                <Link href="/mindar"
                    style={{ textDecoration: "underline", position: "fixed", top: 40, left: 222, color: "white", zIndex: 9999 }}><span>Mindar</span></Link>
                <PaDaKaPanyHeader />
                {children}
            </body>
        </html>
    )
}
